# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Deploy
on:
  release:
    types: [published]

permissions: {}

jobs:
  vsce:
    name: VS Code Marketplace
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: VS Code Marketplace
      url: https://marketplace.visualstudio.com/items?itemName=johnbillion.vscode-wordpress-hooks
    permissions:
      contents: read
    env:
      VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: clean install dependencies
        run: npm ci

      - name: deploy
        run: npm run deploy-vsce

  github:
    name: GitHub Milestones
    permissions:
      issues: write # Required for write access to milestones
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-milestones.yml@9203bb0c5423a9a4b395ff5ffd093ba3714d723f # v2.5.1
    with:
      version: ${{ github.event.release.tag_name }}
